### ISSUE TITLE
interested in the project

### ISSUE THREAD

**Issue by trk0293** [GOLDELEC/Huan#4]
hello goldelec, 
 pardon me for writing on issues page, didn't have a better way of reaching out. 

I am raqhav working for Qualcomm  from San Francisco, US. I am interested in your project and willing to join the project. let me know if you're interested. 

if you're interested leave a mail to trk0293@gmail.com
raqhav.

**Comment by GOLDELEC** [comment]
@trk0293  Hi raqhav, I'm glad that you are interested in the project , and you are welcome to join the project. For the detail,  I  have sent you an email.

GOLDELEC
